//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsuReplayExtractor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsuReplayExtractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find {0} map hashes.
        /// </summary>
        internal static string InformFailedMapHashCount {
            get {
                return ResourceManager.GetString("InformFailedMapHashCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract {0} replays.
        /// </summary>
        internal static string InformFailedReplayCount {
            get {
                return ResourceManager.GetString("InformFailedReplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures have been saved into &apos;FailedMapMatches.txt&apos; or &apos;FailedExtractsPath.txt&apos;.
        /// </summary>
        internal static string InformFailedResultPaths {
            get {
                return ResourceManager.GetString("InformFailedResultPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering existing maps from osu!....
        /// </summary>
        internal static string InformMapsGathering {
            get {
                return ResourceManager.GetString("InformMapsGathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing API key, will not be searching online....
        /// </summary>
        internal static string InformMissingAPIKey {
            get {
                return ResourceManager.GetString("InformMissingAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering replays....
        /// </summary>
        internal static string InformReplayGathering {
            get {
                return ResourceManager.GetString("InformReplayGathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find beatmap online.
        /// </summary>
        internal static string InformSearchAPIFailed {
            get {
                return ResourceManager.GetString("InformSearchAPIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure your API key is correct and have Internet access before trying again..
        /// </summary>
        internal static string InformSearchAPIFailureMessage {
            get {
                return ResourceManager.GetString("InformSearchAPIFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online search failed because the server returned: {0}.
        /// </summary>
        internal static string InformSearchAPIFailureReponse {
            get {
                return ResourceManager.GetString("InformSearchAPIFailureReponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped online search. Please add an API key under &apos;apikey.txt&apos; to enable online searching..
        /// </summary>
        internal static string InformSearchAPISkip {
            get {
                return ResourceManager.GetString("InformSearchAPISkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to search for beatmap online.
        /// </summary>
        internal static string InformUsingSearchAPI {
            get {
                return ResourceManager.GetString("InformUsingSearchAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        internal static string PromptExit {
            get {
                return ResourceManager.GetString("PromptExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your osu folder path. (e.g. C:\osu!).
        /// </summary>
        internal static string PromptInstallPath {
            get {
                return ResourceManager.GetString("PromptInstallPath", resourceCulture);
            }
        }
    }
}
